routes/web.php
<?php
Auth::routes();
Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware'=> ['web','auth']], function(){
    Route::get('/home', function(){
        if (Auth::user()->nivel == 0) {
            $users = Auth::user()->id;
            $user = App\Ficha::all();
            $u = $user[0]->id_user; 
            $con = App\Concurso::all();
            return view('home', compact('users','u','con'));
        } else if (Auth::user()->nivel == 1){
            $users = App\User::all(); 
            $con = App\Concurso::all();
            return view('adminhome', compact('users','con'));
        }else if(Auth::user()->nivel == 3){
            $Juser = App\User::all(); 
            return view('juradohome');
        }else{
            return "algo está errado";
        }
    });
});
//ADMIN
    Route::resource('admin', 'AdminController')->middleware('auth');
    //GERENCIAR USUARIOS
    route::get('/adm/Participantes', function(){
        $users = App\User::all();
        return view('adminPart', compact('users'));
    })->name('adminParticipantes');
    //CONCURSO
    route::get('/adm/CriarConcurso', function(){
        return view('concurso');
    })->name('concurso');
    route::get('/adm/Jurados', function(){
        $Juser = App\User::all(); 
        return view('juradoConcurso', compact('Juser'));
    })->name('ConcJur');
    Route::POST("/home/Concurso", "ConcursoController@create")->name("CriarConcurso");
    route::get("/home/envioJu", "ConcursoController@InserirJurado")->name("InJu");
//FIM ADMIN

//PARTICIPANTE
    route::get("/home/ficha", function(){
        $users = Auth::user()->id;
        //$ficha = \App\ficha::getId();
        return view("ficha",compact('users'));
    })->name("ficha");

    Route::POST("/home/Fichas", "ParticipanteController@create")->name("Criarficha");
//FIM PARTICIPANTE

//JURADO

//FIM JURADO
//Route::post('ficha/cria','Controller@criarFicha')->name('criarJurado');

resources/views/adminAdc.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Cadastro de Jurado') }}</div>
                <div class="card-body">
                    <form method="get" action="{{ route('admin.create') }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nome') }}</label>
                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
                                @if ($errors->has('email'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="telefone" class="col-md-2 col-form-label text-md-right">{{ __('Telefone') }}</label>
                            <div class="col-md-4">
                                <input id="telefone" type="telefone" class="form-control{{ $errors->has('telefone') ? ' is-invalid' : '' }}" name="telefone" value="{{ old('telefone') }}">
                                @if ($errors->has('telefone'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('telefone') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <label for="nivel" class="col-md-2 col-form-label text-md-right">{{ __('Nível') }}</label>
                            <div class="col-md-4">
                                <select name="nivel" id="nivel" class="form-control{{ $errors->has('nivel') ? ' is-invalid' : '' }}">
                                    <option disabled>Selecione o nivel<option>
                                    <option value='0' >Participante<option>
                                    <option value='3'>Jurado<option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>
                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                                @if ($errors->has('password'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>
                            <div class="col-md-6">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required>
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>

                    <a href="{{route('admin.index')}}" > Voltar </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/adminPart.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Todos os usuários cadastrados</div>
                <div class="card-body">
                    <table class='table table-hover table-bordered'>
                        <thead>
                            <tr>
                                <th width='5'>Nº</th>
                                <th>Nome </th>
                                <th>Email</th>
                                <th>Nível</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $key => $value)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$value->name}}</td>
                                <td>{{$value->email}}</td>
                                <td>{{$value->nivel}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/adminhome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        
            <div class='row'>
            <div class="card">
                <div class="card-header">Admin funções</div>
                    <a class="btn" href="{{route('adminParticipantes')}}">Criar Participante/Jurados</button><br>
                    <a class="btn" href="{{route('adminParticipantes')}}">Gerenciar Usuários</a><br>
                    <a class="btn" href="{{route('concurso')}}">Criar concurso</a><br>
                    <!--<button class="btn">Concursos </button>-->
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="alert alert-success" role="alert">
                        <p> Você está logado como Administrador.</p>
                    </div>
                    <table class='table table-hover table-bordered'>
                        <thead>
                            <tr>
                                <th width='5'>Nº</th>
                                <th>Nome </th>
                                <th>Email</th>
                                <th>Nível</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($users as $key => $value)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$value->name}}</td>
                                <td>{{$value->email}}</td>
                                <td>{{$value->nivel}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            @foreach ($con as $key => $value )
                <div class='card'>
                <div class="card-header">Concurso {{$value->nome}}</div>
                <div class="card-body">
                    <div class="alert alert-warning" role="alert">         
                        Veja o edital <a href="{{$value->edital}}">Clique aqui</a>                       
                        <p>Data de encerramento:{{$value->dataEncerra}}</p>
                        <p>Data de final:{{$value->dataFinal}}</p>
                        <a class='btn' href="{{route('ConcJur')}}" > Ver mais informações </a >
                    </div>
                </div>
                </div>
            @endforeach
            </div>
        
    </div>
</div>
@endsection

resources/views/concurso.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('CriarConcurso')}}">
                        @csrf
                        <!--Nome -->
                        <div class="form-group row">
                            <label for="nome" class="col-md-4 col-form-label text-md-right">{{ __('Nome do Concurso') }}</label>
                            <div class="col-md-6">
                                <input id="nome" type="text" class="form-control{{ $errors->has('nome') ? ' is-invalid' : '' }}" name="nome" value="{{ old('nome') }}" required autofocus>
                                @if ($errors->has('nome'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('nome') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- edital -->
                        <div class="form-group row">
                            <label for="edital" class="col-md-4 col-form-label text-md-right">{{ __('Edital') }}</label>
                            <div class="col-md-6">
                                <input id="edital" type="text" class="form-control{{ $errors->has('edital') ? ' is-invalid' : '' }}" name="edital" required>
                                @if ($errors->has('Edital'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('Edital') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Data de Encerra -->
                        <div class="form-group row">
                            <label for="dataEncerra" class="col-md-4 col-form-label text-md-right">{{ __('Data de Encerramento') }}</label>
                            <div class="col-md-6">
                                <input id="dataEncerra" type="date" class="form-control{{ $errors->has('dataEncerra') ? ' is-invalid' : '' }}" name="dataEncerra" required>
                                @if ($errors->has('dataEncerra'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('dataEncerra') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Data de Final -->
                        <div class="form-group row">
                            <label for="dataFinal" class="col-md-4 col-form-label text-md-right">{{ __('Data Final') }}</label>
                            <div class="col-md-6">
                                <input id="dataFinal" type="date" class="form-control{{ $errors->has('dataFinal') ? ' is-invalid' : '' }}" name="dataFinal" required>
                                @if ($errors->has('dataFinal'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('dataFinal') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Criar Concurso -->
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Criar concurso') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    <a href="{{route('admin.index')}}" > Voltar </a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/ficha.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Ficha de inscrição ') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('Criarficha')}}">
                        @csrf
                        <!--Endereço -->
                        <div class="form-group row">
                            <label for="endereco" class="col-md-4 col-form-label text-md-right">{{ __('Endereço') }}</label>
                            <div class="col-md-6">
                                <input id="endereco" type="text" class="form-control{{ $errors->has('endereco') ? ' is-invalid' : '' }}" name="endereco" value="{{ old('endereco') }}" required autofocus>
                                <input id="id" type="hidden" class="form-control" name="id_user" value="{{$users}}">
                                @if ($errors->has('endereco'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('endereco') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Telefone -->
                        <div class="form-group row">
                            <label for="telefone" class="col-md-4 col-form-label text-md-right">{{ __('Telefone') }}</label>

                            <div class="col-md-6">
                                <input id="telefone" type="text" class="form-control{{ $errors->has('telefone') ? ' is-invalid' : '' }}" name="telefone" required>

                                @if ($errors->has('telefone'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('telefone') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Data de Nascimento -->
                        <div class="form-group row">
                            <label for="dataNasc" class="col-md-4 col-form-label text-md-right">{{ __('Data de Nascimento') }}</label>
                            <div class="col-md-6">
                                <input id="dataNasc" type="date" class="form-control{{ $errors->has('dataNasc') ? ' is-invalid' : '' }}" name="dataNasc" required>
                                @if ($errors->has('dataNasc'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('dataNasc') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <!-- Instrumento -->
                        <div class="form-group row">
                            <label for="instrumento" class="col-md-4 col-form-label text-md-right">{{ __('Instrumento') }}</label>

                            <div class="col-md-6">
                                <input id="instrumento" type="text" class="form-control" name="instrumento" required>
                            </div>
                        </div>
                        <!-- Link -->
                        <div class="form-group row">
                            <label for="link" class="col-md-4 col-form-label text-md-right">{{ __('Link do Youtube') }}</label>

                            <div class="col-md-6">
                                <input id="link" type="link" class="form-control" name="link" required>
                            </div>
                        </div>
                        <!-- Mensagem -->
                        <div class="form-group row">
                            <label for="mensagem" class="col-md-4 col-form-label text-md-right">{{ __('Mensagem para comissão') }}</label>

                            <div class="col-md-6">
                                <input id="mensagem" type="text" class="form-control" name="mensagem" required>
                            </div>
                        </div>
                        <!-- Criar ficha -->
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Criar ficha') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif  
                    <div class="alert alert-success" role="alert">
                        <p> Você está logado como participante.</p>
                    </div>
                    <div class="alert alert-warning" role="alert">
                    @if($u == $users)
                        voce ja criou a ficha 
                    @else
                        Precisa criar sua ficha de participante. <a href="{{route('ficha')}}">Clique aqui</a>
                    @endif
                    </div>
                    
                    @if (session('status'))
                                <div class="alert alert-success" role="alert">
                                    Você jé está cadastro no concurso
                                </div>
                            @endif

                    <!-- Card Concurso-->
                    <div class="card col-6">
                        @foreach ($con as $key => $value )
                            <div class="card-header">Concurso {{$value->nome}}</div>
                            <div class="card-body">
                                <div class="alert alert-warning" role="alert">         
                                    Veja o edital <a href="{{$value->edital}}">Clique aqui</a>                       
                                    <p>Data de encerramento:{{$value->dataEncerra}}</p>
                                    <p>Data de final:{{$value->dataFinal}}</p>

                                    <input type='submit' class='btn btn-success' name='enviar' value='enviar'>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/juradoConcurso.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Todos os usuários cadastrados</div>
                <div class="card-body">
                    <form method='get' action="{{route('InJu')}}">
                    @foreach ($Juser as $key => $value )
                        <input type='hidden' name='concurso' value='1'>
                        <input type='checkbox' name='jurado' value='{{$value->id}}'> {{$value->name}}
                    @endforeach
                    <br>
                        <input type='submit' value=' enviar'>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/juradohome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="alert alert-success" role="alert">
                        <p> Você está logado como jurado.</p>
                    </div>
                    <table class='table table-bordered table-dark'>
                        <tr>
                            <th>ID</th>
                            <th>Participante</th>
                            <th>Qua participante</th>
                            <th>Nota</th>
                        </tr>
                        
                        @foreach ($Juser as $key => $value )
                        <tr>
                            <td>{{$value->id}}</td>
                            <td>{{$value->name}}</td>
                            <td><input type='radio' name='selecao'></td>
                            <td><input type='number' name='nota'></td>
                        </tr>
                        @endforeach
                        

                    <table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection